### ISSUE TITLE
Support pulling dbt version from dependency management config files

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/dbt-action#2]
dbt is distributed as a Python package, which means that it's common for dbt users to have a Python dependency management system in place, like Conda or [Poetry](https://python-poetry.org/). We should support pulling the dbt version from a configuration file (e.g. `poetry.lock`), if one is provided in the repo.

This feature was requested by a user [in this thread](https://materializeinc.slack.com/archives/C03648YB34N/p1675785325298049). For an example of a real dbt deployment using Poetry, see [our internal analytics pipeline](https://github.com/MaterializeInc/analytics).

**Comment by dehume** [comment]
Closing as we decided including this logic within the Github Action itself is less clean that combining this Github Action with [other steps](https://github.com/abatilo/actions-poetry) to configure the environment.
